name: Publish map tiles V2

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare V2 folder
        run: |
          rm -rf v2
          mkdir v2

      - name: Extract V2 tiles
        run: |
          unzip -o orignal_v2_xyz_github.zip -d v2

      - name: Commit V2 tiles
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Publish iHunter V2 in separate folder" || exit 0
          git push
